name: Deployed on Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0 # use the latest version of the action
        with:
          api_key: ${{secrets.HEROKU_API_KEY}}
          email: 'cnovac1441@gmail.com'
          docker_compose_file: ./docker-compose.heroku.yml
          heroku_apps: '[{"imagename":"mccbot","appname":"mcc-discord-bot-actions","apptype":"worker"}]'
        env:
          TOKEN: ${{secrets.TOKEN}}
