name: Deployed on Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Heroku Registry
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:login
      - name: Release to Heroku dev
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:release -a mcc-discord-bot-new worker
      - name: Login to Heroku Registry
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:login

      - name: Pull dev image
        run: docker pull registry.heroku.com/mcc-discord-bot-new/worker

      - name: Push production image
        run: docker push registry.heroku.com/mcc-discord-bot-new/worker

      - name: Push Prod Image
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:release -a mcc-discord-bot-new worker



        #   api_key: ${{secrets.HEROKU_API_KEY}}
        #   email: 'cnovac1441@gmail.com'
        #   docker_compose_file: ./docker-compose.heroku.yml
        #   heroku_apps: '[{"imagename":"mccbot","appname":"mcc-discord-bot-new","apptype":"worker"}]'
        # env:
        #   TOKEN: ${{secrets.TOKEN}}
